name: unasp_ht
description: Made to improve the student's routine.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fancy_bottom_navigation: ^0.3.2
  cloud_firestore: ^0.12.9
  firebase_auth: ^0.11.1+12
  dio: ^3.0.4
  rxdart: ^0.23.1
  bloc_pattern: ^2.4.4
  flutter:
    sdk: flutter

  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.3.0

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Flexo
      fonts:
        - asset: assets/font/Flexo-Medium.otf
